file=open("tops1.txt","w")
file.write("This is file management demo using python.")
file.close()
print("File Written Successfully")
print("********************************************************")
file=open("tops1.txt","r")
print(file.read())
file.close()
print("********************************************************")
file=open("tops1.txt","a")
file.write("\nThis file is now appeded.")
file.close()
print("File Appended Successfully")
print("********************************************************")
print("********************************************************")
file=open("tops1.txt","r")
print(file.read())
file.close()
print("********************************************************")
file=open("tops2.txt","w+")
file.write("This is w+ mode in file operation.")
print("File Current Position : ",file.tell())
file.seek(0)
print("File Content : ",file.read())
file.close()
print("********************************************************")
